server:
  port: 8090
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  jpa:
    open-in-view: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true