server:
  port: 8090
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  jpa:
    open-in-view:
      exclude-patterns: /chat/messasges, /post/detail2
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
